### ISSUE TITLE
how to adjust column width?

### ISSUE THREAD

**Issue by raeuz** [farridav/django-jazzmin#137]
Hi,

Any suggestions about adjusting the column width of table ?  e.g., i want to change the width of columns "Action flag" and "Modified" 

![Screenshot_20200904_120824](https://user-images.githubusercontent.com/9192796/92201346-e613d100-eeae-11ea-8352-29572aaee91e.png)

**Comment by farridav** [comment]
You can use the following CSS in your [custom_css](https://django-jazzmin.readthedocs.io/configuration/#diy-with-custom-cssjs) 

```css
#changelist-form table {
    table-layout: fixed;
}

#changelist-form .djn-checkbox-select-all {
    width: auto;
}
```

Though when it hits the really low breakpoints the table gets all squished, give it a try, and see if it solves your problems, (you can check the breakpoints by resizing the window)
