### ISSUE TITLE
Filter on M2M is incredibly slow

### ISSUE THREAD

**Issue by dhvcc** [farridav/django-jazzmin#319]
When using a filter on M2M with like 20k row the filter is **so slow**
Would be nice not to re-render dropdown items on each click which is happening right now

I was trying to use 
```css
.select2-results__options li:nth-child(n+10){
  display: none;
}
```
To not render all 20k fields, but it's no help because every item is inserted with javascript at runtime

Dropdown is cool and it's search if fast, but the initial "render" of dropdown takes just too long. We should probably handle this in template
